; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[service_links][version] = "2.1"

projects[ctools][version] = "1.0"

projects[google_analytics][version] = "1.2"

projects[mollom][version] = "2.1"

projects[pathauto][version] = "1.1"

projects[prettify][version] = "1.0-beta1"

projects[token][version] = "1.1"

projects[twitter][version] = "3.1"

projects[views][version] = "3.3"

; Themes
projects[adaptivetheme][version] = "2.3"

projects[omega][version] = "3.1"

projects[corolla][version] = "2.2"

projects[libra][version] = "1.0"

